model_params:
  name: 'RNNVAE'
  seq_len: 140
  n_features: 1 #Multiple features problem https://stackoverflow.com/questions/71565854/lstm-autoencoder-set-up-for-multiple-features-using-pytorch

data_params:
  data_path: "data/"
  batch_size: 1
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  num_workers: 0

exp_params:
  weight_decay: 0.0
  kld_weight: 0.1
  manual_seed: 1265

trainer_params:
  min_epochs: from_solution_array
  max_epochs: 250

early_stop:
  monitor: "val_loss"
  patience: 5
  min_delta: 0.00

logging_params:
  name: "RNNVAE"
  save_dir: "logs/"
  db_storage: "logs/solution.db"
