model_params:
  name: 'VanillaVAE'
  in_features: 784
  latent_dims: 128
  out_features: 784


data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 0
  num_workers: 1


exp_params:
  LR: 0.0001
  weight_decay: 0.0
  kld_weight: 0.0005
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"

